[package]
name = "content"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
axum-test = "18.2.1"
clap = { version = "4.5.51", features = ["derive", "env"] }
dotenv = { version = "0.15.0", features = ["clap"] }
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["cors"] }

[dev-dependencies]
insta = { version = "1.43.2", features = ["yaml"] }
