services:
  garage:
    image: docker.io/dxflrs/garage:v2.1.0
    ports:
      - "3900:3900"
    restart: unless-stopped
    volumes:
      - ./dev/garage.toml:/etc/garage.toml

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-config.yaml"]
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics endpoint
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    restart: unless-stopped
