services:
  setup:
    build:
      context: .
      dockerfile: Dockerfile-setup
    command: ["/bin/setup", "setup", "env"]
    network_mode: host
    environment:
      - GARAGE_CONFIG_FILE=/etc/garage.toml
      - ENV_FILE=/tmp/env/.env
      - BUCKET_ENDPOINT=http://0.0.0.0:3900
    volumes:
      - ./dev/garage.toml:/etc/garage.toml
      - garage-meta:/var/lib/garage/meta
      - ./local.env/:/tmp/env/
    profiles:
      - all
      - dev
  garage:
    image: docker.io/dxflrs/garage:v2.1.0
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    restart: unless-stopped
    tty: true
    networks:
      - garage-network
    volumes:
      - ./dev/garage.toml:/etc/garage.toml
      - garage-meta:/var/lib/garage/meta
      - garage-data:/var/lib/garage/data
    profiles:
      - dev
      - all
  content:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - ./local.env/:/opt/app/
    networks:
      - garage-network
    depends_on:
      setup:
        condition: service_completed_successfully
    profiles:
      - all
  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    depends_on:
      - garage
    volumes:
      - ./dev/garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
    profiles:
      - dev
      - all

volumes:
  garage-meta:
  garage-data:

networks:
  garage-network:
    driver: bridge
