{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "content.fullname" . }}
  labels:
    {{- include "content.labels" . | nindent 4 }}
type: Opaque
data:
  KEY_ID: {{ .Values.secrets.s3KeyId | b64enc | quote }}
  SECRET_KEY: {{ .Values.secrets.s3SecretKey | b64enc | quote }}
  SIGNING_KEY: {{ .Values.secrets.signingKey | b64enc | quote }}
{{- end }}
